config/routes.rb
Rails.application.routes.draw do

  get 'books/index',to:'books#index', as: 'books_index'
  get 'books/new',to:'books#new', as: 'books_new'
  get 'books/:id/show',to:'books#show', as: 'books_show'
  get 'books/:id/edit',to:'books#edit', as: 'books_edit'
  get 'books/create',to:'books#create', as: 'books_create'
  get 'books/update',to:'books#update', as: 'books_update'
  get 'books/destroy',to:'books#destroy', as: 'books_destroy'
  get 'books/report',to:'books#report', as: 'books_report'

  get 'genres/index',to:'genres#index', as: 'genres_index'
  get 'genres/new',to:'genres#new', as: 'genres_new'
  get 'genres/:id/show',to:'genres#show', as: 'genres_show'
  get 'genres/:id/edit',to: 'genres#edit', as: 'genres_edit'
  get 'genres/create',to:'genres#create', as: 'genres_create'
  get 'genres/update',to:'genres#update', as: 'genres_update'
  get 'genres/destroy',to:'genres#destroy', as: 'genres_destroy'

  resources :books
  resources :genres

  root 'books#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to  :genre
  validates_presence_of :title,:synopsis,:value,:number_of_pages,:genre_id
  validates :value ,numericality: {greater_than: 0.0 }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  #------------------------------------------------------------------------

  def index
    @books = Book.all
  end

  #------------------------------------------------------------------------

  def new
    @book = Book.new
  end

  #------------------------------------------------------------------------

  def show
    @book = Book.find(params[:id])
  end

  #------------------------------------------------------------------------

  def edit
    @book = Book.find(params[:id])
  end

  #------------------------------------------------------------------------

  def create
    @books = Book.new(books_params)
    respond_to do |format|
      if @books.save
        format.html { redirect_to books_index_path, notice: 'Done' }
      else
        format.html { render :new }
      end
    end
  end
  #------------------------------------------------------------------------

  def update
    @books = Book.find(params[:id])
    respond_to do |format|
      if @books.update(books_params)
        format.html { redirect_to books_index_path, notice: 'Done' }
      else
        format.html { render :edit }
      end
    end
  end

  #------------------------------------------------------------------------
  def destroy
    @books = Book.find(params[:id])
    @books.destroy

    respond_to do |format|
      format.html { redirect_to books_index_path, notice: 'Done' }
    end
  end
  #------------------------------------------------------------------------
  def report
    @books = Book.all
    @report_ultimo_livro= Book.last

    report_maior_livro = 0
    @nome_maior_livro = ""
    @report_livro_mais_caro =0
    @report_total_de_livros = 0
    @report_total_de_valor = 0
    @report_total_de_paginas =0
    @genero_mais_ultilizado = 0
    aux_genre = []
    aux_genre_2 = 0

    @books.each do |book|

      @report_total_de_livros = @report_total_de_livros + 1
      @report_total_de_valor = book.value + @report_total_de_valor
      @report_total_de_paginas =book.number_of_pages + @report_total_de_paginas

      if book.number_of_pages > report_maior_livro
        report_maior_livro = book.number_of_pages
        @nome_maior_livro = book.title
      end

      if book.value >  @report_livro_mais_caro
        @report_livro_mais_caro = book.value
      end

      aux_genre = Book.where(genre_id:book.genre_id)

      if aux_genre.length > aux_genre_2
      @genero_mais_ultilizado = book.genre.name
      end

    end
  end
  #------------------------------------------------------------------------
  private

  def books_params
    params.require(:book).permit(:title,:synopsis,:value,:number_of_pages,:genre_id)
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  #------------------------------------------------------------------------

  def index
    @genres = Genre.all
  end

  #------------------------------------------------------------------------
  def new
    @genre = Genre.new
  end

  #------------------------------------------------------------------------
  def show
    @genre = Genre.find(params[:id])
  end

  #------------------------------------------------------------------------
  def edit
    @genre = Genre.find(params[:id])
  end

  #------------------------------------------------------------------------
  def create
    @genres = Genre.new(genre_params)
    respond_to do |format|
      if @genres.save
        format.html { redirect_to genres_index_path, notice: 'Done' }
      else
        format.html { render :new }
      end
    end
  end
 #------------------------------------------------------------------------
  def update
    @genres = Genre.find(params[:id])
    respond_to do |format|
      if @genres.update(genre_params)
        format.html { redirect_to genres_index_path, notice: 'Done' }
      else
        format.html { render :edit }
      end
    end
  end

 #------------------------------------------------------------------------  def destroy
  def destroy
    @genres = Genre.find(params[:id])
    @genres.destroy

    respond_to do |format|
      format.html { redirect_to genres_index_path, notice: 'Done' }
    end
  end
#------------------------------------------------------------------------
  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/books/_form.html.erb
<%= form_with(model: books, local: true) do |form| %>

  <div>
    <%= form.label :"title:" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :"synopsis:"%>
    <%= form.text_area :synopsis %>
  </div>

  <div>
    <%= form.label :"value:" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.label :"number_of_pages:" %>
    <%= form.text_field :number_of_pages %>
  </div>

  <div>
    <%= form.label :"genre:" %>
    <%= form.collection_select(:genre_id, Genre.all, :id, :name) %>
  </div>

  <%= form.submit books.new_record? ? 'Add new book' : 'Edit Book', class: 'button' %>
<% end %>

app/views/books/edit.html.erb
<div class="panel">
  <div class="header"><h2>Edit Book</h2></div>
  <%= render 'form', books: @book%>
</div>

app/views/books/index.html.erb
<div class="panel">
  <table class="table">

    <thead>
    <tr>
      <th>Id:</th>
      <th>Title:</th>
      <th>Value:</th>
      <th>Number of pages:</th>
      <th>Genre:</th>
    </tr>
    </thead>

    <tbody>
    <% @books.each do |book| %>


      <tr>
        <td><%= book.id %></td>
        <td><%= book.title %></td>
        <td><%= book.value %></td>
        <td><%= book.number_of_pages %></td>
        <td><%= book.genre.name %></td>

        <td style="text-align: right">
          <%= link_to 'Delete Book', book, class: 'button', method: :delete, data: {confirm: 'Você tem certeza?'} %>
          <%= link_to 'Edit Book', books_edit_path(book), class: 'button' %>
          <%= link_to 'Show Book', book, class: 'button' %>
        </td>

      </tr>
    <% end %>
    </tbody>

  </table>

  <div class="panelT panelaligright">
    <%= link_to 'Add new book', books_new_path, class: 'button' %>
  </div>

  <% if flash.count.positive? %>
    <div class="panel">
      <p id="notice">
        <%= notice %>
      </p>
    </div>
  <% end %>

</div>

app/views/books/new.html.erb
<div class="panelT">
<div class="header"><h2>New Book</h2></div>
<%= render 'form', books: @book %>
</div>

app/views/books/report.html.erb
<div class="panel">

  <div class="panel">
    <h2>Book with greater number of pages:</h2>
    <div class="panel"><%= @nome_maior_livro %></div>
  </div>
  <div class="panel">
    <h2>Most expensive book:</h2>
    <div class="panel"><%= @report_livro_mais_caro %></div>
  </div>

  <div class="panel">
    <h2>Total catalog books:</h2>
    <div class="panel"><%= @report_total_de_livros %></div>
  </div>

  <div class="panel">
    <h2>Total value of books:</h2>
    <div class="panel"><%= @report_total_de_valor %></div>
  </div>

  <div class="panel">
    <h2>Total pages added:</h2>
    <div class="panel"><%= @report_total_de_paginas %></div>
  </div>

  <div class="panel">
    <h2>Last Book Catalog:</h2>
    <div class="panel"><%= @report_ultimo_livro.title %></div>
  </div>

  <div class="panel">
    <h2>Most used genre:</h2>
    <div class="panel"><%= @genero_mais_ultilizado %></div>
  </div>

</div>

app/views/books/show.html.erb
<div class="panel">

  <div class="panel">
    <h2>Id:</h2>
    <div class="panel"><%= @book.id %></div>
  </div>
  <div class="panel">
    <h2>Title:</h2>
    <div class="panel"><%= @book.title %></div>
  </div>
  <div class="panel">
    <h2>Synopsis:</h2>
    <div class="panel"><textarea readonly><%= @book.synopsis %></textarea></div>
  </div>
  <div class="panel">
    <h2>Genre:</h2>
    <div class="panel"> <%= @book.genre.name %> </div>
  </div>
  <div class="panel">
    <h2>Value:</h2>
    <div class="panel"> U$: <%= @book.value %></div>
  </div>
  <div class="panel">
    <h2>Number of pages:</h2>
    <div class="panel"> <%= @book.number_of_pages %> pag. </div>
  </div>

</div>

app/views/genres/_form.html.erb
<%= form_with(model: genres, local: true) do |form| %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.submit genres.new_record? ? 'New genre' : 'Edit genre', class: 'button' %>
<% end %>

app/views/genres/edit.html.erb
<div class="panel">
  <h2>Edit Genre</h2>
  <%= render 'form', genres: @genre %>
</div>

app/views/genres/index.html.erb
<div class="panel">
  <table class="table">
    <thead>
    <tr>
      <th>Id:</th>
      <th>Name:</th>
    </tr>
    </thead>

    <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.id %></td>
        <td><%= genre.name %></td>


        <td style="text-align: right">
          <%= link_to 'Delete genre', genre, class: 'button', method: :delete, data: {confirm: 'Você tem certeza?'} %>
          <%= link_to 'Edit genre', genres_edit_path(genre), class: 'button' %>
          <%= link_to 'Show genre', genre, class: 'button' %>
        </td>
      </tr>
    <% end %>
    </tbody>

  </table>

  <div class="panelT panelaligright">
    <%= link_to 'Add new genre', genres_new_path, class: 'button' %>
  </div>

</div>

app/views/genres/new.html.erb
<div class="panelT">
<h2>New Genre</h2>
<%= render 'form', genres: @genre %>
</div>

app/views/genres/show.html.erb
<div class="panel">
  <div class="panel">
    <h2>Id:</h2>
    <div class="panel"><%= @genre.id %></div>
  </div>
  <div class="panel">
    <h2>Name:</h2>
    <div class="panel"><%= @genre.name%></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catalog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="panel header"> <h1>Book Catalog:</h1></div>
  <ul class="menu-container">
    <li class="menu-item">
      <%= link_to 'Books list', books_index_path %>
    </li>
    <li class="menu-item">
      <%= link_to 'Genre list', genres_index_path %>
    </li>
    <li class="menu-item">
    <%= link_to 'Report', books_report_path %>
    </li>
  </ul>
    <%= yield %>
  </body>
</html>